user:
  jay:
    username: 周杰伦
    password: 1234abcd!
  william:
    username: william
    password: 1234abcd!



mysql:
  db:autotest
  host:localhost
  password:123456
  port:3306
  user:root

url: http://192.168.0.121